---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    author: shahrukh
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 30008
  selector:
    type: appserver
...
